### ISSUE TITLE
Clicking on hypothesis with GPT under crossing does not work

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/harmonizome-issues#12]
<img width="1180" alt="Screenshot 2024-08-19 at 7 43 52 PM" src="https://github.com/user-attachments/assets/2f62a29e-e6b6-490e-b09b-2c058d4d8d36">
<img width="1198" alt="Screenshot 2024-08-19 at 7 43 43 PM" src="https://github.com/user-attachments/assets/1fda2027-4a40-4dea-ba6e-fb72bfdd1631">

**Comment by AviMaayan** [comment]
https://maayanlab.cloud/Harmonizome/cross

**Comment by u8sand** [comment]
Pretty sure this is now fixed. I did the following:

- increase statement timeout since the query was slow
- add an index to speed up the query

**Comment by diamantido** [comment]
It looks like it's still there. There's some issue in grabbing this set of input genes for some reason (probably the "+"). The GPT hypothesis step is then hanging when trying to submit 0 genes to Enrichr, which is an error that isn't being handled properly.

**Comment by u8sand** [comment]
Maybe an encodeURIComponent is missing
