### ISSUE TITLE
Looks like Harmonizome-KG has two copies of the L1000 chemical perturbation data

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/harmonizome-issues#19]
<img width="1193" alt="Screenshot 2024-09-02 at 10 07 31 PM" src="https://github.com/user-attachments/assets/99cbe375-a99c-4963-80af-0d068c6a4709">

**Comment by jeevangelista** [comment]
the other one are for the consensus signatures. Renaming the edges to reflect this.
